//{{NO_DEPENDENCIES}}
// Von Microsoft Visual C++ generierte Includedatei.
// Verwendet durch Installer.rc
//
#define _USE_DECLSPECS_FOR_SAL          0
#define _USE_ATTRIBUTES_FOR_SAL         0
#define _ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE 0
#define _HAS_EXCEPTIONS                 1
#define _CRT_BUILD_DESKTOP_APP          1
#define __STDC_WANT_SECURE_LIB__        1
#define EPERM                           1
#define ENOENT                          2
#define ESRCH                           3
#define EINTR                           4
#define EIO                             5
#define ENXIO                           6
#define E2BIG                           7
#define _CRT_PACKING                    8
#define ENOEXEC                         8
#define EBADF                           9
#define ECHILD                          10
#define EAGAIN                          11
#define ENOMEM                          12
#define EACCES                          13
#define EFAULT                          14
#define EBUSY                           16
#define EEXIST                          17
#define EXDEV                           18
#define ENODEV                          19
#define _SAL_VERSION                    20
#define ENOTDIR                         20
#define EISDIR                          21
#define ENFILE                          23
#define EMFILE                          24
#define ENOTTY                          25
#define EFBIG                           27
#define ENOSPC                          28
#define ESPIPE                          29
#define EROFS                           30
#define EMLINK                          31
#define EPIPE                           32
#define EDOM                            33
#define EDEADLK                         36
#define ENAMETOOLONG                    38
#define ENOLCK                          39
#define ENOSYS                          40
#define ENOTEMPTY                       41
#define _ARGMAX                         100
#define EADDRINUSE                      100
#define EADDRNOTAVAIL                   101
#define EAFNOSUPPORT                    102
#define IDS_APP_TITLE                   103
#define EALREADY                        103
#define EBADMSG                         104
#define ECANCELED                       105
#define ECONNABORTED                    106
#define ECONNREFUSED                    107
#define ECONNRESET                      108
#define IDC_INSTALLER                   109
#define EDESTADDRREQ                    109
#define EHOSTUNREACH                    110
#define EIDRM                           111
#define EINPROGRESS                     112
#define EISCONN                         113
#define ELOOP                           114
#define EMSGSIZE                        115
#define ENETDOWN                        116
#define ENETRESET                       117
#define ENETUNREACH                     118
#define ENOBUFS                         119
#define ENODATA                         120
#define ENOLINK                         121
#define ENOMSG                          122
#define ENOPROTOOPT                     123
#define ENOSR                           124
#define ENOSTR                          125
#define ENOTCONN                        126
#define ENOTRECOVERABLE                 127
#define ENOTSOCK                        128
#define IDD_DIALOG1                     129
#define ENOTSUP                         129
#define EOPNOTSUPP                      130
#define EOTHER                          131
#define EOVERFLOW                       132
#define IDR_BINKW32                     133
#define EOWNERDEAD                      133
#define EPROTO                          134
#define EPROTONOSUPPORT                 135
#define EPROTOTYPE                      136
#define ETIME                           137
#define IDB_BITMAP1                     138
#define ETIMEDOUT                       138
#define ETXTBSY                         139
#define EWOULDBLOCK                     140
#define IDI_ICON                        141
#define IDS_VERSION_X_X                 143
#define IDS_STRING144                   144
#define IDS_STRING_X_X_X_X              144
#define IDS_VERSION_X_X_X_X             144
#define IDS_VERSION_ALREADY_INSTALLED   145
#define IDS_UPDATEABLE                  146
#define IDS_STRING147                   147
#define IDS_STRING148                   148
#define IDS_STRING149                   149
#define IDS_STRING150                   150
#define IDS_STRING151                   151
#define IDS_STRING152                   152
#define IDS_STRING153                   153
#define IDS_STRING154                   154
#define IDS_STRING155                   155
#define IDS_STRING156                   156
#define IDS_STRING157                   157
#define IDS_STRING158                   158
#define IDS_STRING159                   159
#define IDS_STRING160                   160
#define IDS_STRING161                   161
#define IDS_STRING162                   162
#define IDS_STRING163                   163
#define IDS_STRING164                   164
#define IDS_STRING165                   165
#define IDS_STRING166                   166
#define IDS_STRING167                   167
#define _SECURECRT_FILL_BUFFER_PATTERN  0xFE
#define IDC_CHOOSE                      1000
#define IDC_INSTALLDIR                  1001
#define IDC_VERSION                     1002
#define IDC_INSTALL                     1003
#define IDC_UNINSTALL                   1004
#define IDC_STATUS                      1005
#define IDC_PLUGINS                     1006
#define IDC_LINK                        1012
#define IDC_MYVERSION                   1013
#define IDC_HINT                        1014
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1016
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
